### ISSUE TITLE
PythonPractice/turtle/tree.py文件编译不过，“l”没有定义

### ISSUE THREAD

**Issue by zndxall** [MDGSF/PythonPractice#1]

**Comment by MDGSF** [comment]
@zndxall 我这了都可以啊，你把错误贴出来看下

**Comment by zndxall** [comment]
![image](https://user-images.githubusercontent.com/48979083/56349278-c8cb5d80-61fa-11e9-87ca-88b90c09be7a.png)

**Comment by MDGSF** [comment]
@zndxall bug 已修复。
